version: '2.1'
orbs:
  node: circleci/node@14.15.1
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/catwalk
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  test_my_app:
    jobs:
      - test