version: '2.1'
orbs:
  node: circleci/welcome-orb@0.4.1
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/catwalk
    steps:
      - checkout
      - run: npx test
workflows:
  test_my_app:
    jobs:
      - test